const categories = [
  { title: "Any Category", id: "0" },
  { title: "General Knowledge", id: "9" },
  { title: "Cartoon", id: "32" },
  { title: "Anime", id: "31" },
  { title: "Gadgets", id: "30" },
  { title: "Comics", id: "29" },
  { title: "Vehicles", id: "28" },
  { title: "Animals", id: "27" },
  { title: "Celebrities", id: "26" },
  { title: "Art", id: "25" },
  { title: "Politics", id: "24" },
  { title: "History", id: "23" },
  { title: "Geography", id: "22" },
  { title: "Sports", id: "21" },
  { title: "Mythology", id: "20" },
  { title: "Mathematics", id: "19" },
  { title: "Computers", id: "18" },
  { title: "Science and Nature", id: "17" },
  { title: "Board Games", id: "16" },
  { title: "Video Games", id: "15" },
  { title: "Television", id: "14" },
  { title: "Musicals & Theatres", id: "13" },
  { title: "Music", id: "12" },
  { title: "Film", id: "11" },
  { title: "Books", id: "10" },
];

export default categories;
